name: CI - Pokemon API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Instalar dependências
        run: poetry install --no-interaction --no-root

      - name: Rodar Lint (Ruff)
        run: poetry run ruff check .

      - name: Rodar Testes
        run: poetry run pytest -q

      - name: Build da imagem Docker
        run: docker build -t pokemon-api .
